//
// Created by luria on 15/10/2022.
//

#ifndef PACMANSFML_GAMESSTATESENUM_H
#define PACMANSFML_GAMESSTATESENUM_H

#endif // PACMANSFML_GAMESSTATESENUM_H

enum class AvailableStates
{
  MAIN_MENU,
  IN_GAME,
  LEADERBOARD,
  GAME_OVER,
};